### ISSUE TITLE
How to get files in npy on own dataset?

### ISSUE THREAD

**Issue by miibotree** [betterze/StyleSpace#11]
I trained a stylegan2 model on my own dataset.
How to get attribute, label, semantic_top_32 files on my own dataset?
How data formats are organized？

**Comment by betterze** [comment]
Sorry for the delay. Please refer to  [localized-channels](https://github.com/betterze/StyleSpace#localized-channels) to generate semantic_top_32, and [attribute specific channels](https://github.com/betterze/StyleSpace#attribute-specific-channels) for attribute.

I generate label file manually. It depends on the semantic segmentation model you are using. Please refer to  [localized-channels](https://github.com/betterze/StyleSpace#localized-channels) step 3 for detail.
