### ISSUE TITLE
how to real image manipulation?

### ISSUE THREAD

**Issue by leeisack** [betterze/StyleSpace#12]
Hello, I'm looking forward to your paper.
If you look at your paper, there is a case that uses real face manipulation instead of a generated image, please tell me how to do input other image it with code.

**Comment by woctezuma** [comment]
![Manipulation of Real Images](https://i.ibb.co/w7QTTNF/2021-10-06-15-05-15.png)

**Comment by betterze** [comment]
Dear Lee and Wok,

Thank you for your interest in our work.

We trained an image encoder by ourself when we published the paper. But now, there are better image encoder, please refer to [e4e encoder](https://github.com/omertov/encoder4editing).

Maybe use e4e encoder to invert the image to stylegan2 latent space, then use our method to manipulate the image.

Best Wishes,

Alex
