### ISSUE TITLE
Could you please share the semantic_top_32 file of locally active channel?

### ISSUE THREAD

**Issue by Qiulin-W** [betterze/StyleSpace#14]
It takes quite a long time and to generate the gradient maps, is it possible to share the top32 channels that are locally active at different facial parts as shown in Figure 3 in the paper? Thanks a lot!

**Comment by betterze** [comment]
Thank you for interest in our work. The semantic_top_32 for ffhq is [here] (https://github.com/betterze/StyleSpace/blob/main/npy/ffhq/semantic_top_32) is here.
