### ISSUE TITLE
S space

### ISSUE THREAD

**Issue by PangziZhang523** [betterze/StyleSpace#16]
Thanks for the interesting work.
I would like to ask how did you get s space? In the paper, it is said that it is obtained by the In-domain gan method, but I read the In-domain gan paper to get W space. Is s space obtained on W space or is it a separate space?

**Comment by woctezuma** [comment]
Not sure if relevant, but you can find this in the original StyleGAN paper:

![Figure 1](https://i.ibb.co/CKTvrrP/2021-12-16-10-15-50.png)

![Text](https://i.ibb.co/JjWN2T6/2021-12-16-10-17-10.png)

References:
- [1] https://arxiv.org/abs/1812.04948
- [2] https://github.com/NVlabs/stylegan

**Comment by PangziZhang523** [comment]
Thank you for the answer. My understanding is that the 'style' in stylegan refers to the style parameter in Adain, which is not the same as the latent space in stylespace.

**Comment by betterze** [comment]
The way to transfer w+ space to s space could be found [here](https://github.com/betterze/StyleSpace/blob/main/manipulate.py#L229).

Each w in the w+ space (18 w) will be passed to an affine transformation (A in this [figure](https://github.com/betterze/StyleSpace/issues/16#issuecomment-995584194)) to get the s parameters. The detailed mapping between w+ and s could be found in our supplemnetary Table 2.

**Comment by PangziZhang523** [comment]
Thanks for the answer, I probably understand the relationship between s and w.
Then  [https://github.com/betterze/StyleSpace/blob/main/manipulate.py#L229](here) can also transfer w to s, right? , Because they are all affine transformations, but w is a 1*512 vector, and w+ is 18 w.
Another question is how Inversion gets s when comparing in Figure 18. If it is from w to s, the results of w and s should be the same because there is no editing.

**Comment by betterze** [comment]
1. The [function](https://github.com/betterze/StyleSpace/blob/main/manipulate.py#L229 ) can transfer w+ to s. To get w+ from w, just repeat the function 18 times, so the shape will be from (1,512) to (1, 18, 512). In this way, we can transfer w -> w+ ->  s. 

2. In figure 18, we compare different spaces for inversion. Given the same input image, we invert it to w, w+ or s space separately. The information is flowed from image to latent space (image->s->w+), rather than from latent space to image (w+->s->image). Since there are affine transformations from w+ to s, so inversion to w+ will be more constrained than that to s, the s reconstruction will be slightly better than w+ reconstruction.

**Comment by PangziZhang523** [comment]
Thank you for the answer. How did you get the s in Inversion in Figure 18 directly? There is something unclear here. Could you please answer it again? That is image->s.

**Comment by betterze** [comment]
In figure 18, the latent codes are obtained through latent optimization. [Here](https://github.com/NVlabs/stylegan2/blob/master/projector.py) is standard latent optimization code from StyleGAN2 paper (section 5). It optimizes in W space, we modify this code to S or W+ space.

If you want to do latent optimization in S space, we suggest you to use the [pytorch implementation](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/main/projector.py), which is easier to play with.

**Comment by PangziZhang523** [comment]
Thanks a lot for answers. 
There is also a problem when looking for the channel of a specific attribute. I only used a male classifier to get the attribute channel which is different from your gender (9, 6). I used 50 positive images, and the layer and channel I found were (8, 223).
![image](https://user-images.githubusercontent.com/56216032/146772305-16e3ddd2-4215-40cc-8e91-5e841ff14982.png)

**Comment by betterze** [comment]
In the paper, we claim that just using 20-30 example images, we can have top 5 accuracy higher than 90%. It is the top 5 accuracy, rahter than top 1 accuracy.

For the case you show above, the target channel 9_6 is in rank 5. So for top 5 accuracy, it is a success. For top 1 accuracy, it is a failure.
