### ISSUE TITLE
How to use on car model?

### ISSUE THREAD

**Issue by sarmientoj24** [betterze/StyleSpace#22]
Or a custom model? What would be the prerequisites?

**Comment by betterze** [comment]
I use the [stylegan2-car-config-f.pkl](https://nvlabs-fi-cdn.nvidia.com/stylegan2/networks/stylegan2-car-config-f.pkl) from [here](https://nvlabs-fi-cdn.nvidia.com/stylegan2/networks/).

If you just want to try the manipulation, please try this [nootbook](https://github.com/betterze/StyleSpace/blob/main/StyleSpace_single.ipynb) and change the dataset_name to car. Then change the (lindex,cindex) following the instruction.

**Comment by betterze** [comment]
Thank you for your interest in our work.
