### ISSUE TITLE
About pretrained classifiers

### ISSUE THREAD

**Issue by sarmientoj24** [betterze/StyleSpace#24]
1. Is the pretrained classifiers for car and LSUN bedroom available?
2. How do I create or find a pretrained classifier for a model I trained from scratch?
3. This [notebook](https://github.com/betterze/StyleSpace/blob/main/StyleSpace_advance.ipynb) seems to be very specialized for FFHQ. Any advise or notebook you used for other classes?

Wonderful work!

**Comment by betterze** [comment]
1. [Here](https://github.com/genforce/higan/blob/master/predictors/README.md) are some pretrained classifiers for bedroom. But human face domain has more anotation data to trained classfiers on.
2. The classifiers are trained on external data sets. It will be hard to get them in bedroom domain.
3. Currently, I only create the nootbook for ffhq. You could create simiar notebook for other domains by run [localized-channels detection](https://github.com/betterze/StyleSpace#localized-channels).

**Comment by sarmientoj24** [comment]
Thank you for this. However, I do not completely understand which ones are the pretrained classifier for the bedroom in the link.
