### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by fifi7260** [betterze/StyleSpace#29]
If possible, could you share the pytorch version of GetCode.py? I want to get the latent codes "s" of the pretrained stylegan2-ada model.
[metfaces.pkl](https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/metfaces.pkl)

**Comment by fifi7260** [comment]
I was able to solve it. Thank you.

**Comment by WuYufeng98** [comment]
> I was able to solve it. Thank you.

Can you share your pytorch code ?

**Comment by betterze** [comment]
We implement the single channel manipulation in torch, pls take a look of [here](https://github.com/orpatashnik/StyleCLIP/blob/main/global_torch/manipulate.py).
