### ISSUE TITLE
About the fine-grained control of face editing.

### ISSUE THREAD

**Issue by sunpeng1996** [betterze/StyleSpace#3]
Hi, zongze, good to see you again.

I notice that both in StyleSpace and StyleCLIP, it is difficult to manipulate more fine-grained attributes such as nose (big/small), single and double eyelids, ear size, and so on.
Do you have any ideas about these fine-grained attribute controls?

**Comment by sunpeng1996** [comment]
I have tried in StyleCLIP to control single and double eyelids by typing "double-eyelid man with hair" VS "single-eyelid man with hair", but I failed. :)
Moreover, I notice that in StyleSpace, you mention that there have 10 of 26 attributes including "big nose", which are difficult to be controlled.

**Comment by sunpeng1996** [comment]
Thanks to the excellent work, StyleSpace.
However，it is a new concept and one always explores the S space alone.
Hence, I create a QQ group (754288725) for communication of StyleSpace.
I hope everybody can communicate and brainstorm here.
@betterze

**Comment by betterze** [comment]
Dear sunpeng1996, 

Thank you for your interest in our work. 

1. In supplementary table 5, among 26 attributes, 16 attributes can be controled by a single channel. For the other 10 attributes, we can not find a single channel that control these attributes. Big nose is in the 'no disentangled single-channel controls found' group (10/26), which mean we can not find a single channel that control the size of nose. 

2. I agree that for some fine grained controls (for example, double eyelids), our method could not control them. To the best of my knowledge, I can not recall any method that can control size of nose or double eyelids. Maybe the StyleGAN just capture a sub distribution of real face distribution (mode collapse), our method is based on StyleGAN, so we can not manipulate some attributes. Or StyleGAN can control these attributes, but we just dont have a good way to discover these controls. This is a hard question, I dont have a solid answer. 

Best Wishes,

Zongze

**Comment by sunpeng1996** [comment]
Dear zongze, thank you for your reply. 
I hope to have more communication with you in the future and look forward to your better work.
