### ISSUE TITLE
How to calculate the gradient map, what are the specific details

### ISSUE THREAD

**Issue by WoshiBoluo** [betterze/StyleSpace#4]
Your work is really good! 
But I have some detail question.
When detect locally-active style channels, how to calculate the gradient map, what are the specific details?

**Comment by sunpeng1996** [comment]
+1，it's better to have a more detailed readme doc.

**Comment by betterze** [comment]
Thank you for your interest in our work. 

The way to calculate the gradient map w.r.t the S channels is in [invert_mask.py](https://github.com/betterze/StyleSpace/blob/main/invert_mask.py). You are welcome to take a look of it.

**Comment by sunpeng1996** [comment]
Thanks. However, when I run invert_mask.py. 

I meet the following error.

`Setting up TensorFlow plugin "fused_bias_act.cu": Loading... Done.
Setting up TensorFlow plugin "upfirdn_2d.cu": Loading... Done.
layer_num:  18
(1, 3, 32, 32)
0
Traceback (most recent call last):
  File "cal_grad.py", line 275, in <module>
    tmp= d[s_names2[i]] #[:,0,0,channel_index,0]
KeyError: 'G_synthesis_2/256x256/Conv0_up/add:0'`

**Comment by sunpeng1996** [comment]
By the way, zongze, can you share your face segmentation model?

**Comment by sunpeng1996** [comment]
I guess the s_names3 should be s_names2 in Line 272?  When I change to s_names2, I meet the following error.

![image](https://user-images.githubusercontent.com/11503624/115994299-042e6d00-a609-11eb-9970-b1005a6d482f.png)

**Comment by betterze** [comment]
Dear Sunpeng1996,

I rerun the invert_mask.py, everything works find. You rewrite the the codes into another file called 'cal_grad.py', right? I do not know what did you change, but please try the original 'invert_mask.py'. If the 'invert_mask.py' reports error, please inform me the error.

Here is the [face parsing model](https://github.com/zllrunning/face-parsing.PyTorch). The speed of this method is slow, I use multiple gpu to run this 'invert_mask.py' in parallel. 

Best Wishes,

Alex

**Comment by miibotree** [comment]
line 271-272 did exists an error:
for i in range(len(s_names2)):
    d[s_names3[i]]=all_s[i][img_index:(img_index+batch_size)]

since s_names2 removes all tensors with names contains 'ToRGB',  
using len(s_names2) cannot traverse all needed tensors.

**Comment by Zhangxinnian** [comment]
@betterze @miibotree @sunpeng1996 
Hello, I have encountered some problems with calculating the gradient map. 
1. Where does S_100K in invert_mask.py come from? Is it made through GetCode.py? 
2. When I run inver_mask.py using S made by GetCode.py, I will also encounter KeyError:'G_synthesis_2/256x256/Conv0_up/add:0' 
3. When I modify to G_synthesis_1/256x256/Conv0_up/add: After 0, there will be: AssertionError: x_shape = [None, 512], init_data shape = [1, 512] This kind of error. When I modify x_shape = [None, 512] to [1,512], the error dx=[None] will appear again.
Excuse me, how should I solve these problems, or where I did it wrong in the beginning！Looking forward to your reply！
Best Wishes，

**Comment by betterze** [comment]
@miibotree @sunpeng1996 @WoshiBoluo The codes](https://github.com/betterze/StyleSpace#localized-channels) for localized channels are online now. Sorry for the delay.

**Comment by jweihe** [comment]
> Do you have the pytorch version of this part? I don't quite understand the author's approach
