### ISSUE TITLE
Can you share your dataset?

### ISSUE THREAD

**Issue by yagizcolak** [betterze/StyleSpace#5]
Hello,
Can you share the dataset you used while training your latent directions? How many samples did you use? Thanks.

**Comment by betterze** [comment]
Dear Yağız Çolak,

Thank you for your interest in our work. 

You mean the method for 'Detecting attribute-specific channels' in section 5? We use the pretrained classifers from [here](https://drive.google.com/drive/folders/1MvYdWCBuMfnoYGptRH-AgKLbPTsIQLhl) to annotation 100K generated images. An example of annotation could be found in [here](https://github.com/betterze/StyleSpace/blob/main/npy/ffhq/attribute). And the way to use the attribute annotation can be found in [colab](https://github.com/betterze/StyleSpace/blob/main/StyleSpace_advance.ipynb) attribute specific channels section.

Best Wishes,

Alex

**Comment by renrenzsbbb** [comment]
Dear Alex
Thanks for your grreat work. Can you shape the complete relationships between channel and semantic category. Thanks.

**Comment by betterze** [comment]
@renrenzsbbb Sorry for the late reply. No all channels contain semantic meaning. Sometimes, it is hard to describe the function of a certain channel. 

On the other hand, we can know the functional region of each channel.  For example, we may know one channel mainly affect hair, but we don't if it change the hair color or hair length. Please refer to [our paper](https://arxiv.org/abs/2011.12799) section 4 for detail. 

The ./npy/ffhq/semantic_top_32 file contain the annotation for each channel. Please refer to [localized channel](https://github.com/betterze/StyleSpace#localized-channels) to generate channel annotation, and [this nootbook](https://github.com/betterze/StyleSpace/blob/main/StyleSpace_advance.ipynb) for visualizing the effect of most activated channels of a certrain attribute.
